spring.application.name=api

# The map to the new SwiftGrid vault
spring.datasource.url=jdbc:postgresql://localhost:5432/swiftgrid_db

# Your pgAdmin login credentials (change 'root' if your password is different)
spring.datasource.username=postgres
spring.datasource.password=joshua231

# Hibernate Settings: Let Java build the tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true